# Generated by Django 5.0.3 on 2024-08-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absent', '0002_alter_absent_responser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absent',
            name='response_context',
            field=models.TextField(blank=True),
        ),
    ]
